const ZH = {
  brand: "CueTuck · 唤词",
  search: "搜索",
  launcher: "启动器",
  login: "登录",
  loggedIn: "已登录",
  square: "提示词广场",
  local: "本地提示词",
  settings: "设置",
  create: "新建",
  publish: "发布提示词",
  refresh: "刷新",
  model: "模型",
  allModels: "全部模型",
  myCategories: "我的分类",
  exploreCategories: "探索分类",
  allPrompts: "全部提示词",
  tabAll: "全部",
  tabRecent: "最近",
  tabFavorite: "收藏",
  tabRecommended: "推荐",
  tabLatest: "最新",
  tabHot: "热门",
  edit: "编辑",
  use: "使用",
  favorite: "收藏",
  unfavorite: "取消收藏",
  remove: "删除",
  open: "打开",
  download: "下载",
  localFirst: "本地优先",
  moreActions: "右键查看更多操作",
  emptyLocal: "本地库是空的",
  emptyFiltered: "没有匹配的提示词",
  emptyFilteredHint: "试试其他关键词、分类或模型，已有内容不会受到影响。",
  emptyRecent: "还没有最近使用",
  emptyFavorite: "还没有本地收藏",
  emptySquare: "广场还没有内容",
  emptyOffline: "暂时看不到广场列表",
  emptyLocalHint: "点右上角「新建提示词」即可写入本机。",
  emptySquareHint: "本地提示词仍然可用。",
  switchLight: "切换浅色主题",
  switchDark: "切换深色主题",
  languageToggle: "切换到 English",
  settingsGeneral: "常规",
  settingsAccount: "账号与广场",
  settingsShortcuts: "快捷键",
  settingsSync: "同步",
  settingsModels: "AI 与模型",
  settingsData: "数据与备份",
  settingsNetwork: "网络与代理",
  settingsAppearance: "外观",
  settingsPrivacy: "隐私与安全",
  settingsUpdates: "更新",
};

const EN = {
  brand: "CueTuck",
  search: "Search",
  launcher: "Launcher",
  login: "Sign in",
  loggedIn: "Signed in",
  square: "Prompt Square",
  local: "Local library",
  settings: "Settings",
  create: "New",
  publish: "Publish",
  refresh: "Refresh",
  model: "Model",
  allModels: "All models",
  myCategories: "My categories",
  exploreCategories: "Browse categories",
  allPrompts: "All prompts",
  tabAll: "All",
  tabRecent: "Recent",
  tabFavorite: "Favorites",
  tabRecommended: "Recommended",
  tabLatest: "Latest",
  tabHot: "Hot",
  edit: "Edit",
  use: "Use",
  favorite: "Favorite",
  unfavorite: "Unfavorite",
  remove: "Delete",
  open: "Open",
  download: "Download",
  localFirst: "Local first",
  moreActions: "Right-click for more actions",
  emptyLocal: "The local library is empty",
  emptyFiltered: "No matching prompts",
  emptyFilteredHint: "Try another keyword, category, or model. Your existing content is unchanged.",
  emptyRecent: "Nothing used recently",
  emptyFavorite: "No local favorites yet",
  emptySquare: "Square has no items yet",
  emptyOffline: "Square list is unavailable",
  emptyLocalHint: "Use New in the header to write a local prompt.",
  emptySquareHint: "Local prompts still work.",
  switchLight: "Switch to light theme",
  switchDark: "Switch to dark theme",
  languageToggle: "Switch to 中文",
  settingsGeneral: "General",
  settingsAccount: "Account & Square",
  settingsShortcuts: "Shortcuts",
  settingsSync: "Sync",
  settingsModels: "AI & models",
  settingsData: "Data & backup",
  settingsNetwork: "Network & proxy",
  settingsAppearance: "Appearance",
  settingsPrivacy: "Privacy & security",
  settingsUpdates: "Updates",
};

export function uiText(lang, key) {
  const pack = lang === "en" ? EN : ZH;
  return pack[key] ?? ZH[key] ?? key;
}
