<template>
  <div class="identity-settings">
    <section class="panel"><div class="panel-heading"><h2>注册策略</h2><button :disabled="busy||loading" @click="reload">重新加载</button></div><p v-if="error" class="error-banner" role="alert">{{ error }}</p><p v-if="message" role="status" class="success-message">{{ message }}</p><p v-if="loading" class="empty-state">正在加载…</p>
      <form v-else-if="policy" @submit.prevent="save"><label class="identity-toggle"><input v-model="policy.registration_open" type="checkbox" :disabled="busy" data-testid="registration-open">允许新账号注册</label><p class="muted">同时控制邮箱注册和首次 OAuth 账号创建；已有账号仍可登录。邮箱注册需要先启用邮件服务。所有邮箱账号必须验证后创建。</p><footer><span class="muted">版本 {{ policy.revision }}</span><button class="primary" :disabled="busy||!policyDirty" data-testid="identity-save">保存策略</button></footer></form>
    </section>
    <section class="panel"><div class="panel-heading"><h2>邀请管理员</h2><span class="badge">仅所有者</span></div><p class="muted">仅邀请新邮箱成为运营管理员或审核员；已有用户请在用户管理中调整权限。邀请 30 分钟有效，接受前可以撤销。</p>
      <form class="invite-form" @submit.prevent="invite"><fieldset :disabled="busy"><div class="identity-grid"><label>收件邮箱<input v-model="email" type="email" required maxlength="254" data-testid="invite-email"></label><label>角色<select v-model="role"><option value="reviewer">内容审核员</option><option value="admin">运营管理员</option></select></label><label>你的当前密码<input v-model="password" type="password" required autocomplete="current-password" maxlength="512" data-testid="invite-password"></label></div><button class="primary" data-testid="invite-send" :disabled="!email||!password">发送邀请邮件</button></fieldset></form>
    </section>
    <section class="panel"><div class="panel-heading"><h2>邀请记录</h2><span class="badge">{{ total }} 条</span><button :disabled="busy||listLoading" @click="loadList(offset)">刷新</button></div><p v-if="listError" role="alert" class="error-banner">{{ listError }}</p><p v-if="listLoading" class="empty-state">正在加载…</p><div v-else class="table-scroll"><table class="data-table"><thead><tr><th>邮箱</th><th>角色</th><th>状态</th><th>失效时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{ item.email }}</td><td>{{ item.role==='admin'?'运营管理员':'内容审核员' }}</td><td>{{ labels[item.status]||item.status }}</td><td>{{ new Date(item.expires_at).toLocaleString() }}</td><td><button v-if="item.status==='pending'" :disabled="busy" @click="revoke(item)">撤销</button><span v-else>—</span></td></tr><tr v-if="!items.length"><td colspan="5" class="empty-state">尚无邀请记录</td></tr></tbody></table></div><footer class="pagination"><span>{{ total }} 条</span><button :disabled="busy||listLoading||offset===0" @click="loadList(Math.max(0,offset-25))">上一页</button><button :disabled="busy||listLoading||offset+25>=total" @click="loadList(offset+25)">下一页</button></footer><p class="muted">这里是邀请状态，不是邮件送达状态；发送情况请到邮件服务查看。</p></section>
  </div>
</template>
<script setup>
import {computed,onMounted,ref} from 'vue';import {getIdentityPolicy,saveIdentityPolicy,listInvitations,inviteAdmin,revokeInvitation} from './adminApi.js';
const emit=defineEmits(['busy-change']);const policy=ref(null),saved=ref(''),loading=ref(false),busy=ref(false),error=ref(''),message=ref(''),email=ref(''),role=ref('reviewer'),password=ref(''),items=ref([]),total=ref(0),offset=ref(0),listLoading=ref(false),listError=ref('');const labels={pending:'待接受',used:'已接受',revoked:'已撤销',expired:'已过期'};
const policyDirty=computed(()=>!!policy.value&&JSON.stringify(policy.value)!==saved.value);const hasUnsavedChanges=computed(()=>policyDirty.value||!!email.value||!!password.value);defineExpose({hasUnsavedChanges,isBusy:busy});function setBusy(value){busy.value=value;emit('busy-change',value);}
function accept(value){if(typeof value?.registration_open!=='boolean'||!Number.isInteger(value.revision))throw Error('策略响应无效');policy.value=value;saved.value=JSON.stringify(value);}
async function load(){loading.value=true;error.value='';try{accept(await getIdentityPolicy());}catch(e){error.value=e.message;}finally{loading.value=false;}}
function reload(){if(policyDirty.value&&!window.confirm('放弃未保存的注册策略？'))return;load();}
async function save(){if(busy.value||!policyDirty.value)return;setBusy(true);error.value='';try{const result=await saveIdentityPolicy({...policy.value});if(result.revision!==policy.value.revision+1)throw Error('服务端未确认保存');accept(result);message.value='注册策略已保存，邮箱和 OAuth 新账号入口同时生效。';}catch(e){error.value=e.message;}finally{setBusy(false);}}
async function loadList(start=offset.value){listLoading.value=true;listError.value='';try{const result=await listInvitations(start);items.value=result.items;total.value=result.total;offset.value=start;}catch(e){listError.value=e.message;}finally{listLoading.value=false;}}
async function invite(){if(busy.value)return;if(!window.confirm(`邀请 ${email.value} 成为${role.value==='admin'?'运营管理员':'审核员'}并发送验证邮件？`))return;setBusy(true);error.value='';message.value='';try{const result=await inviteAdmin({email:email.value.trim(),role:role.value,current_password:password.value});if(result.status!=='pending')throw Error('服务端未确认邀请');email.value='';message.value='邀请已创建并排队发信，接受前不会创建管理员账号。';await loadList(0);}catch(e){error.value=e.message;}finally{password.value='';setBusy(false);}}
async function revoke(item){if(!window.confirm(`撤销发送给 ${item.email} 的邀请？`))return;setBusy(true);try{await revokeInvitation(item.id,{revision:item.revision});await loadList();}catch(e){listError.value=e.message;}finally{setBusy(false);}}
onMounted(()=>{load();loadList(0);});
</script>
<style scoped>
.identity-settings{display:grid;gap:24px}.identity-settings form{padding:20px 24px}.identity-toggle{display:flex;align-items:center;gap:10px}.identity-settings footer{display:flex;gap:16px;align-items:center;justify-content:flex-end;margin-top:20px}.identity-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin-bottom:20px}.identity-settings select{font:inherit;color:inherit;background:#fff;border:1px solid #dce1e4;padding:10px 12px;border-radius:7px;min-height:42px;width:100%;margin-top:8px}.identity-settings input:not([type=checkbox]){width:100%;min-width:0}@media(max-width:700px){.identity-grid{grid-template-columns:1fr}}
</style>
