import {mount,flushPromises} from '@vue/test-utils';import {it,expect,afterEach,vi} from 'vitest';import MailSettings from './MailSettings.vue';import {setAdminApiTransport,resetAdminApi} from './adminApi.js';
let w;afterEach(()=>{w?.unmount();resetAdminApi();vi.restoreAllMocks();});const config=()=>({revision:1,enabled:false,host:'smtp.example.com',port:465,tls:'implicit',from:'noreply@example.com',username:'user',secret_configured:true,last_test:null});
it('fills QQ connection parameters without changing identities or automatically saving or sending',async()=>{
  const transport=vi.fn(r=>r.kind==='mailList'?{items:[],total:0}:{...config(),port:587,tls:'starttls'});setAdminApiTransport(transport);
  w=mount(MailSettings);await flushPromises();await w.get('[data-testid=mail-secret]').setValue('fixture-authorization-code');
  transport.mockClear();await w.get('[data-testid=mail-qq-preset]').trigger('click');
  expect(w.get('[data-testid=mail-host]').element.value).toBe('smtp.qq.com');expect(w.get('[data-testid=mail-port]').element.value).toBe('465');expect(w.get('[data-testid=mail-tls]').element.value).toBe('implicit');
  expect(w.get('[data-testid=mail-from]').element.value).toBe('noreply@example.com');expect(w.get('[data-testid=mail-username]').element.value).toBe('user');expect(w.get('[data-testid=mail-secret]').element.value).toBe('fixture-authorization-code');
  expect(w.get('.mail-toggle input').element.checked).toBe(false);expect(transport).not.toHaveBeenCalled();expect(w.text()).toContain('不是 QQ 登录密码');expect(w.get('[data-testid=mail-save]').attributes('disabled')).toBeDefined();
});
it('does not expose saving defaults after mail configuration fails',async()=>{setAdminApiTransport(r=>{if(r.kind==='mailList')return {items:[],total:0};throw Error('加载失败')});w=mount(MailSettings);await flushPromises();expect(w.find('[data-testid=mail-save]').exists()).toBe(false);expect(w.text()).toContain('加载失败');});
it('requires password to save and preserves draft but clears password on conflict',async()=>{let sent;setAdminApiTransport(r=>{if(r.kind==='mailList')return {items:[],total:0};if(r.kind==='mailConfig')return config();sent=r.config;throw Error('版本冲突')});w=mount(MailSettings);await flushPromises();await w.get('[data-testid=mail-host]').setValue('new.example.com');expect(w.get('[data-testid=mail-save]').attributes('disabled')).toBeDefined();await w.get('[data-testid=mail-password]').setValue('my-password');await w.get('.mail-form').trigger('submit');await flushPromises();expect(sent.host).toBe('new.example.com');expect(sent.secret_configured).toBeUndefined();expect(w.vm.hasUnsavedChanges).toBe(true);expect(w.get('[data-testid=mail-password]').element.value).toBe('');expect(w.text()).toContain('版本冲突');});
it('confirms the recipient and never labels queued mail as delivered',async()=>{const send=vi.fn(()=>({id:'test',status:'queued'}));setAdminApiTransport(r=>r.kind==='mailList'?{items:[],total:0}:r.kind==='mailTest'?send(r):config());w=mount(MailSettings);await flushPromises();await w.get('[data-testid=mail-recipient]').setValue('qa@example.com');vi.spyOn(window,'confirm').mockReturnValue(false);await w.get('.mail-test').trigger('submit');expect(send).not.toHaveBeenCalled();window.confirm.mockReturnValue(true);await w.get('.mail-test').trigger('submit');await flushPromises();expect(send.mock.calls[0][0].config.to).toBe('qa@example.com');expect(w.text()).toContain('测试邮件已排队');expect(w.text()).not.toContain('发送成功');});
