<template>
  <div class="mail-settings">
    <section class="panel"><div class="panel-heading"><h2>SMTP 邮件服务</h2><span class="badge">{{ configState }}</span><button :disabled="busy||loading" @click="reload">重新加载</button></div>
      <p class="muted">用于注册验证、管理员邀请和找回密码。仅允许公网 SMTP 与加密连接；保存不发信，密钥不返回浏览器。</p><p v-if="error" class="error-banner" role="alert">{{ error }}</p><p v-if="message" class="success-message" role="status">{{ message }}</p><p v-if="loading" class="empty-state" role="status">正在加载…</p>
      <form v-else-if="draft" class="mail-form" @submit.prevent="save"><fieldset :disabled="busy"><div class="mail-grid"><label>SMTP 主机<input v-model="draft.host" required maxlength="253" placeholder="smtp.example.com" data-testid="mail-host"></label><label>端口<select v-model.number="draft.port"><option :value="465">465</option><option :value="587">587</option></select></label><label>加密方式<select v-model="draft.tls"><option value="implicit">隐式 TLS</option><option value="starttls">强制 STARTTLS（不允许降级）</option></select></label><label>发件邮箱<input v-model="draft.from" type="email" required maxlength="254"></label><label>SMTP 用户名<input v-model="draft.username" autocomplete="off" required maxlength="254"></label><label>SMTP 密码<input v-model="secret" type="password" autocomplete="new-password" maxlength="4096" :placeholder="hasSecret ? '已加密，留空保留' : '首次配置时填写'"></label></div>
        <label class="mail-toggle"><input v-model="draft.enabled" type="checkbox">启用业务邮件投递（关闭时仍可主动测试）</label><p class="muted">修改 SMTP 后，旧配置排队邮件不会擅自切换发件身份，需要重新发起对应流程。</p>
        <footer class="mail-save"><span class="muted">版本 {{ draft.revision }}</span><label>当前管理员密码<input v-model="password" type="password" autocomplete="current-password" maxlength="512" data-testid="mail-password"></label><button class="primary" :disabled="!hasUnsavedChanges||!password" data-testid="mail-save">保存配置</button></footer>
      </fieldset></form>
      <form v-if="draft" class="mail-test" @submit.prevent="test"><h3>发送固定测试邮件</h3><p class="muted">只发送到下方指定地址。返回排队不等于成功，SMTP 已接受也不保证进入收件箱。</p><label>测试收件邮箱<input v-model="recipient" type="email" required maxlength="254" :disabled="busy" data-testid="mail-recipient"></label><button :disabled="busy||hasUnsavedChanges||!hasSecret" data-testid="mail-test">发送测试邮件</button><small v-if="hasUnsavedChanges" class="muted">先保存或放弃草稿再测试。</small></form>
    </section>
    <section class="panel"><div class="panel-heading"><h2>投递记录</h2><span class="badge">{{ total }} 条</span><button :disabled="busy||listLoading" @click="loadList(offset)">刷新</button></div><form class="mail-filters" @submit.prevent="loadList(0,true)"><label>邮箱或记录 ID<input v-model="query" maxlength="254"></label><label>状态<select v-model="status"><option value="">全部</option><option v-for="(label,key) in labels" :key="key" :value="key">{{ label }}</option></select></label><button :disabled="busy||listLoading">查询</button></form><p v-if="listError" role="alert" class="error-banner">{{ listError }}</p><p v-if="listLoading" class="empty-state">正在加载记录…</p>
      <div v-else class="table-scroll"><table class="data-table"><thead><tr><th>收件人 / 用途</th><th>状态</th><th>尝试</th><th>更新时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{ item.recipient }}<small>{{ purposes[item.purpose] || item.purpose }} · SMTP v{{ item.config_revision }}</small></td><td>{{ labels[item.status] || item.status }}<small>{{ item.error }}</small></td><td>{{ item.attempts }} / 3</td><td>{{ date(item.updated_at) }}</td><td><button :disabled="busy" @click="details(item.id)">详情</button><button v-if="item.status==='failed'&&item.attempts<3&&new Date(item.expires_at)>new Date()" :disabled="busy" @click="retry(item)">立即重试</button></td></tr><tr v-if="!items.length"><td colspan="5" class="empty-state">没有匹配的投递记录</td></tr></tbody></table></div>
      <footer class="pagination"><span>{{ total ? offset+1 : 0 }}–{{ Math.min(offset+25,total) }} / {{ total }}</span><button :disabled="busy||listLoading||offset===0" @click="loadList(Math.max(0,offset-25))">上一页</button><button :disabled="busy||listLoading||offset+25>=total" @click="loadList(offset+25)">下一页</button></footer>
    </section>
    <section v-if="selected" class="panel mail-detail"><div class="panel-heading"><h2>投递尝试</h2><button @click="selected=null">关闭</button></div><p>{{ selected.item.recipient }} · {{ selected.item.id }}</p><p class="muted">网络中断后投递结果可能未知，重试可能产生相同邮件；验证凭据仍只能使用一次。</p><ul><li v-for="attempt in selected.attempts" :key="attempt.id">第 {{ attempt.attempt }} 次 · {{ labels[attempt.status] || attempt.status }} · {{ date(attempt.created_at) }}<p>{{ attempt.error }}</p></li></ul></section>
  </div>
</template>
<script setup>
import {computed,onMounted,ref} from 'vue';import {getMailConfig,saveMailConfig,testMail,listMail,getMail,retryMail} from './adminApi.js';
const emit=defineEmits(['busy-change']);const draft=ref(null),saved=ref(''),hasSecret=ref(false),secret=ref(''),password=ref(''),recipient=ref(''),lastTest=ref(null),loading=ref(false),busy=ref(false),error=ref(''),message=ref('');
const items=ref([]),total=ref(0),offset=ref(0),query=ref(''),status=ref(''),applied=ref({q:'',status:''}),listLoading=ref(false),listError=ref(''),selected=ref(null);let listVersion=0;
const labels={queued:'排队中',sending:'发送中',accepted:'SMTP 已接受',failed:'失败',expired:'已过期',config_changed:'配置变化，需重新发起'},purposes={test:'测试邮件',registration:'注册验证',reset:'密码重置',invitation:'管理员邀请'};
const hasUnsavedChanges=computed(()=>!!draft.value&&(JSON.stringify(draft.value)!==saved.value||!!secret.value));const configState=computed(()=>!draft.value?'未加载':!hasSecret.value?'未配置密钥':lastTest.value?.config_revision===draft.value.revision?labels[lastTest.value.status]:'当前版本未测试');defineExpose({hasUnsavedChanges,isBusy:busy});
function accept(data){if(!Number.isInteger(data?.revision)||typeof data.enabled!=='boolean')throw Error('邮件配置响应无效');const {secret_configured,last_test,...config}=data;draft.value=config;saved.value=JSON.stringify(config);hasSecret.value=secret_configured;lastTest.value=last_test;secret.value='';password.value='';}
function setBusy(value){busy.value=value;emit('busy-change',value);}function date(value){return new Date(value).toLocaleString();}
async function load(){loading.value=true;error.value='';try{accept(await getMailConfig());}catch(e){error.value=e.message;}finally{loading.value=false;}}
function reload(){if(hasUnsavedChanges.value&&!window.confirm('放弃未保存的邮件配置？'))return;load();}
async function save(){if(busy.value||!hasUnsavedChanges.value||!password.value)return;setBusy(true);error.value='';message.value='';try{const result=await saveMailConfig({...draft.value,password:secret.value,current_password:password.value});if(result.revision!==draft.value.revision+1)throw Error('服务端未确认保存');accept(result);message.value='配置已保存，尚未发送测试邮件。';}catch(e){error.value=e.message;}finally{password.value='';setBusy(false);}}
async function test(){if(busy.value||hasUnsavedChanges.value||!hasSecret.value)return;if(!window.confirm(`向 ${recipient.value} 发送一封固定测试邮件？`))return;setBusy(true);error.value='';message.value='';try{const result=await testMail({revision:draft.value.revision,to:recipient.value.trim()});if(result.status!=='queued')throw Error('服务端未确认入队');message.value='测试邮件已排队，请刷新投递记录查看结果。';await loadList(0);}catch(e){error.value=e.message;}finally{setBusy(false);}}
async function loadList(start=offset.value,apply=false){const version=++listVersion;listLoading.value=true;listError.value='';const filters=apply?{q:query.value,status:status.value}:applied.value;try{const data=await listMail({...filters,offset:start});if(version!==listVersion)return;items.value=data.items;total.value=data.total;offset.value=start;applied.value={...filters};const test=items.value.find(i=>i.purpose==='test');if(test)lastTest.value=test;}catch(e){if(version===listVersion)listError.value=e.message;}finally{if(version===listVersion)listLoading.value=false;}}
async function details(id){setBusy(true);try{selected.value=await getMail(id);}catch(e){listError.value=e.message;}finally{setBusy(false);}}
async function retry(item){if(!window.confirm('立即重试这封邮件？收件人与内容不会改变，累计最多 3 次。'))return;setBusy(true);try{await retryMail(item.id,{revision:item.revision});await loadList();}catch(e){listError.value=e.message;}finally{setBusy(false);}}
onMounted(()=>{load();loadList(0);});
</script>
<style scoped>
.mail-settings{display:grid;gap:24px}.mail-form,.mail-test,.mail-detail>p,.mail-detail>ul{padding:20px 24px}.mail-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.mail-toggle{display:flex;align-items:center;gap:10px;margin:24px 0}.mail-save{display:flex;gap:16px;align-items:end;justify-content:flex-end;padding-top:20px;border-top:1px solid #e4e7eb}.mail-save label{max-width:300px}.mail-test{border-top:1px solid #e4e7eb}.mail-test>label{display:block;max-width:420px;margin:20px 0}.mail-filters{display:flex;gap:16px;align-items:end;padding:20px 24px}.mail-filters label:first-child{flex:1}.mail-settings select{font:inherit;color:inherit;background:white;padding:10px 12px;border:1px solid #dce1e4;border-radius:7px;min-height:42px;width:100%;margin-top:8px}.mail-settings input:not([type=checkbox]){width:100%;min-width:0}.mail-settings td small{display:block;color:#7c858d;max-width:320px;overflow-wrap:anywhere;margin-top:6px}.mail-settings td button{margin:2px}.mail-detail p{overflow-wrap:anywhere}@media(max-width:650px){.mail-grid{grid-template-columns:1fr}.mail-save,.mail-filters{flex-direction:column;align-items:stretch}.mail-save label{max-width:none}}
</style>
