<template>
  <div class="mock-billing"><p class="mock-banner"><strong>MOCK · 测试环境</strong> 这里不扣款、不授予真实 Pro。模拟记录独立保存，重启后保留。<span v-if="enabled===false">当前后端未启用模拟，历史只读。</span></p>
    <div class="mock-tabs" role="tablist" aria-label="模拟账单"><button v-for="(label,key) in tabs" :key="key" role="tab" :aria-selected="kind===key" :disabled="busy" @click="switchTab(key)">{{ label }}</button></div>
    <p v-if="error" class="error-banner" role="alert">{{ error }}</p><p v-if="message" class="success-message" role="status">{{ message }}</p>
    <section v-if="kind==='batches'&&enabled" class="panel"><div class="panel-heading"><h2>生成测试码批次</h2></div><form class="mock-form" @submit.prevent="generate"><fieldset :disabled="busy"><div class="mock-grid"><label>批次名称<input v-model="batchName" required maxlength="80" data-testid="mock-batch-name"></label><label>码数量<input v-model.number="count" type="number" min="1" max="100" required></label><label>每码使用额度<input v-model.number="uses" type="number" min="1" max="1000" required></label><label>有效天数<input v-model.number="days" type="number" min="1" max="365" required></label></div><p class="muted">每个账号每码仅可使用一次；明码仅在生成后显示一次，列表无法恢复。</p><button class="primary" data-testid="mock-generate">生成测试码</button></fieldset></form></section>
    <section v-if="codes.length" class="panel"><div class="panel-heading"><h2>一次性测试码 · {{ codes.length }} 个</h2><button @click="copyCodes">复制全部</button><button @click="clearCodes">清除显示</button></div><p class="muted">请先保存。这些 TEST- 码不适用于真实兑换接口。</p><pre class="generated-codes">{{ codes.join('\n') }}</pre></section>
    <section class="panel"><div class="panel-heading"><h2>{{ tabs[kind] }}</h2><form class="mock-search" @submit.prevent="load(0)"><input v-model="query" aria-label="搜索模拟记录" placeholder="邮箱、名称、ID 或订单结果"><button :disabled="busy||loading">搜索 / 刷新</button></form></div><p v-if="loading" class="empty-state">正在加载…</p>
      <div v-else class="table-scroll"><table class="data-table"><thead><tr v-if="kind==='entitlements'"><th>账号</th><th>真实权益（只读）</th><th>Mock 权益</th><th>操作</th></tr><tr v-else-if="kind==='orders'"><th>模拟订单</th><th>账号</th><th>结果</th><th>原因 / 操作者</th><th>时间</th></tr><tr v-else><th>批次</th><th>状态</th><th>使用次数 / 总额度</th><th>失效时间</th><th>操作</th></tr></thead><tbody><tr v-for="item in items" :key="item.id||item.email">
        <template v-if="kind==='entitlements'"><td>{{ item.email }}</td><td>{{ item.real_pro?'Pro':'未订阅' }}</td><td><span class="badge">Mock · {{ item.mock_pro?'Pro':'未订阅' }}</span></td><td><button :disabled="busy||!enabled" @click="edit(item.email)">模拟操作</button></td></template>
        <template v-else-if="kind==='orders'"><td><small>MOCK</small><br>{{ item.id }}</td><td>{{ item.email }}</td><td>{{ outcomes[item.outcome]||item.outcome }}</td><td>{{ item.reason }}<br><small>{{ item.actor }}</small></td><td>{{ formatDate(item.created_at) }}</td></template>
        <template v-else><td>{{ item.name }}<br><small>{{ item.id }}</small></td><td>{{ Date.parse(item.expires_at)<=Date.now()?'已过期':item.enabled?'启用':'停用' }}</td><td>{{ item.used_count }} / {{ item.code_count*item.uses_per_code }}</td><td>{{ formatDate(item.expires_at) }}</td><td><button :disabled="busy" @click="showBatch(item.id)">详情</button><button :disabled="busy||!enabled" @click="toggle(item)">{{ item.enabled?'停用':'启用' }}</button></td></template>
      </tr><tr v-if="!items.length"><td colspan="5" class="empty-state">暂无{{ tabs[kind] }}</td></tr></tbody></table></div><footer class="pagination"><span>{{ total }} 条 · {{ kind==='entitlements'?'真实权益仅供对照，操作只影响模拟权益':'全部为模拟记录' }}</span><button :disabled="busy||loading||!offset" @click="load(Math.max(0,offset-25))">上一页</button><button :disabled="busy||loading||offset+25>=total" @click="load(offset+25)">下一页</button></footer></section>
    <section v-if="target" class="panel"><div class="panel-heading"><h2>模拟操作 · {{ target }}</h2><button :disabled="busy" @click="target='';changeReason=''">取消</button></div><form class="mock-form" @submit.prevent="change"><fieldset :disabled="busy"><div class="mock-grid"><label>结果<select v-model="outcome"><option v-for="(label,key) in actionOutcomes" :key="key" :value="key">{{ label }}</option></select></label><label>操作原因<input v-model="changeReason" required maxlength="500" data-testid="mock-reason"></label></div><p class="muted">失败/取消不改变模拟权益；重置不影响真实权益。</p><button class="primary" data-testid="mock-change">确认模拟</button></fieldset></form></section>
    <section v-if="detail" class="panel"><div class="panel-heading"><h2>批次详情 · {{ detail.batch.name }}</h2><button @click="detail=null">关闭</button></div><div class="table-scroll"><table class="data-table"><thead><tr><th>测试码提示</th><th>使用 / 每码额度</th></tr></thead><tbody><tr v-for="code in detail.codes" :key="code.id"><td>{{ code.hint }}</td><td>{{ code.uses }} / {{ detail.batch.uses_per_code }}</td></tr></tbody></table><h3>最近 {{ detail.uses_limit }} 条使用记录</h3><table class="data-table"><thead><tr><th>账号</th><th>模拟订单</th><th>使用时间</th></tr></thead><tbody><tr v-for="use in detail.recent_uses" :key="use.order_id"><td>{{ use.email }}</td><td>{{ use.order_id }}</td><td>{{ formatDate(use.created_at) }}</td></tr><tr v-if="!detail.recent_uses.length"><td colspan="3">暂无使用</td></tr></tbody></table></div></section>
  </div>
</template>
<script setup>
import {computed,onMounted,ref} from 'vue';import {listMockBilling,changeMockBilling,createMockBatch,getMockBatch,updateMockBatch} from './adminApi.js';
const emit=defineEmits(['busy-change']);const tabs={entitlements:'账号权益',orders:'模拟订单',batches:'测试兑换码'};const actionOutcomes={success:'模拟成功 / 授予模拟 Pro',failure:'模拟失败',cancel:'模拟取消',reset:'重置模拟权益'};const outcomes={...actionOutcomes,redeem:'测试码兑换'};
const kind=ref('entitlements'),items=ref([]),total=ref(0),offset=ref(0),query=ref(''),enabled=ref(null),loading=ref(false),busy=ref(false),error=ref(''),message=ref(''),target=ref(''),outcome=ref('success'),changeReason=ref(''),batchName=ref(''),count=ref(10),uses=ref(1),days=ref(30),codes=ref([]),detail=ref(null);let requestKey='',requestId='',batchKey='',batchRequest=null,loadVersion=0;
const hasUnsavedChanges=computed(()=>!!target.value||!!batchName.value||!!codes.value.length);defineExpose({hasUnsavedChanges,isBusy:busy});function setBusy(value){busy.value=value;emit('busy-change',value);}const formatDate=v=>new Date(v).toLocaleString();
async function load(start=offset.value){const version=++loadVersion;loading.value=true;error.value='';try{const result=await listMockBilling(kind.value,{q:query.value,offset:start});if(version!==loadVersion)return;items.value=result.items;total.value=result.total;offset.value=start;enabled.value=result.enabled;}catch(e){if(version===loadVersion)error.value=e.message;}finally{if(version===loadVersion)loading.value=false;}}
function switchTab(value){if(kind.value===value)return;if(hasUnsavedChanges.value&&!window.confirm('离开将放弃草稿和一次性测试码，确认已保存需要的码？'))return;target.value='';changeReason.value='';batchName.value='';codes.value=[];detail.value=null;query.value='';kind.value=value;load(0);}
function edit(email){target.value=email;changeReason.value='';outcome.value='success';}
async function change(){if(busy.value)return;const config={email:target.value,outcome:outcome.value,reason:changeReason.value};const key=JSON.stringify(config);if(!window.confirm(`确认对 ${target.value} 执行${actionOutcomes[outcome.value]}？不改变真实权益。`))return;if(key!==requestKey){requestKey=key;requestId=crypto.randomUUID();}setBusy(true);error.value='';try{const result=await changeMockBilling({...config,request_id:requestId});if(result.mock!==true||!result.order?.id)throw Error('服务端未确认模拟结果');message.value='模拟操作已记录，真实权益未改变。';target.value='';changeReason.value='';requestKey='';await load();}catch(e){error.value=e.message;}finally{setBusy(false);}}
async function generate(){if(busy.value)return;if(codes.value.length&&!window.confirm('新生成会替换当前一次性码显示，确认已经保存？'))return;if(!window.confirm(`生成 ${count.value} 个测试码，每码额度 ${uses.value}，有效 ${days.value} 天？`))return;const key=JSON.stringify([batchName.value,count.value,uses.value,days.value]);if(key!==batchKey){batchKey=key;batchRequest={name:batchName.value,count:count.value,uses_per_code:uses.value,expires_at:new Date(Date.now()+days.value*86400000).toISOString(),request_id:crypto.randomUUID()};}setBusy(true);error.value='';try{const result=await createMockBatch(batchRequest);if(result.mock!==true||!Array.isArray(result.codes))throw Error('服务端未确认生成');codes.value=result.codes;batchName.value='';batchKey='';message.value='测试码已生成，仅当前页面显示一次。';await load(0);}catch(e){error.value=e.message;}finally{setBusy(false);}}
async function toggle(item){if(!window.confirm(`确认${item.enabled?'停用':'启用'}批次 ${item.name}？停用后未使用码不可兑换。`))return;setBusy(true);error.value='';try{await updateMockBatch(item.id,{revision:item.revision,enabled:!item.enabled});await load();}catch(e){error.value=e.message;}finally{setBusy(false);}}
async function showBatch(id){setBusy(true);error.value='';try{detail.value=await getMockBatch(id);}catch(e){error.value=e.message;}finally{setBusy(false);}}
async function copyCodes(){try{await navigator.clipboard.writeText(codes.value.join('\n'));message.value='测试码已复制，请妥善保存。';}catch{error.value='复制失败，请手动选择测试码复制。';}}
function clearCodes(){if(window.confirm('清除后无法恢复明码，确认已经保存？'))codes.value=[];}
onMounted(()=>load(0));
</script>
<style scoped>
.mock-billing{display:grid;gap:20px;min-width:0}.mock-banner{margin:0;background:#fff6e9;border:1px solid #f0dcc0;border-radius:10px;padding:16px;line-height:1.6;font-size:13px}.mock-banner strong{display:block;color:#92652c}.mock-tabs{display:flex;gap:8px;flex-wrap:wrap}.mock-tabs [aria-selected=true]{background:#e8f2ef;color:#176c61}.mock-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.mock-form{padding:24px}.mock-grid label{display:grid;gap:8px}.mock-grid input,.mock-grid select,.mock-search input{min-width:0;width:100%;font:inherit;color:inherit;border:1px solid #dce1e4;border-radius:7px;padding:10px 12px;box-sizing:border-box}.mock-search{display:flex;gap:8px;flex-wrap:wrap}.mock-search input{width:260px}.generated-codes{padding:20px;overflow:auto;max-height:280px;font-size:13px}.mock-billing td{overflow-wrap:anywhere}.mock-billing td small{color:#7b858e}.mock-billing .table-scroll h3{margin:20px;font-size:14px}@media(max-width:650px){.mock-grid{grid-template-columns:1fr}.mock-search input{width:100%}}
</style>
