<template>
  <div class="notification-settings">
    <p class="notice">通知仅发送公开风险事件的编号、来源和分数，不发送提示词正文。默认关闭；HTTP / SMTP 接收不等于人工已处理。</p>
    <p v-if="error" role="alert" class="error-banner">{{ error }}</p><p v-if="message" role="status" class="success-message">{{ message }}</p>
    <section class="panel"><div class="panel-heading"><h2>通知渠道与保留策略</h2><button :disabled="busy" @click="load">重新加载</button></div><p v-if="loading" role="status" class="panel-note">正在读取…</p>
      <form v-if="draft" @submit.prevent="save"><fieldset :disabled="busy"><div class="notification-fields">
        <label class="check"><input v-model="draft.email_enabled" type="checkbox" data-testid="notify-email">高风险邮件</label><label>收件邮箱<input v-model="draft.recipient" type="email" placeholder="单一运营邮箱"><small>复用邮件服务中的 SMTP，必须先配置并启用。</small></label>
        <label class="check"><input v-model="draft.webhook_enabled" type="checkbox" data-testid="notify-webhook">高风险 Webhook</label><label>HTTPS Endpoint<input v-model="draft.endpoint" type="password" autocomplete="new-password" data-testid="notify-endpoint" :placeholder="saved.endpoint_configured?'留空保留已加密地址':'https://notify.example.com/events'"><small>{{ saved.webhook_host ? `已配置主机：${saved.webhook_host}` : '未配置地址' }}；不支持查询参数、本机或私网地址。</small></label>
        <label>Webhook 签名密钥<input v-model="draft.secret" type="password" autocomplete="new-password" maxlength="4096" :placeholder="saved.secret_configured?'留空保留原密钥':'至少 16 个字节'" data-testid="notify-secret"><small>HMAC-SHA256 签名；接收方须按投递 ID 去重。</small></label>
        <label>高风险分数阈值<input v-model.number="draft.threshold" type="number" min="1" max="100" required></label><label>每日投递额度<input v-model.number="draft.daily_limit" type="number" min="1" max="1000" required><small>按 UTC 日计算，测试也计入，不回补启用前的历史事件。</small></label>
        <label class="check"><input v-model="draft.retention_enabled" type="checkbox" data-testid="notify-retention">启用运行日志清理</label><label>保留天数<input v-model.number="draft.retention_days" type="number" min="7" max="3650" required><small>仅清理过期终态运行记录，安全操作审计永远保留。清理后需从备份恢复，请先备份。</small></label>
        <label>当前管理员密码<input v-model="draft.current_password" type="password" autocomplete="current-password" maxlength="512" required data-testid="notify-password"></label>
      </div><footer><small>已保存版本 {{ saved.revision }} · {{ saved.active_since ? `采集起点 ${date(saved.active_since)}` : '尚未启用采集' }}</small><button type="submit" class="primary" data-testid="notify-save" :disabled="!dirty">保存配置</button></footer></fieldset></form>
    </section>
    <section v-if="draft" class="panel"><div class="panel-heading"><h2>测试通知</h2></div><div class="notification-tests"><p class="muted">仅向已保存且启用的渠道发送固定测试说明；保存草稿后才可测试。超时可能已投递，重试可能重复，请接收端去重。</p><button :disabled="busy || changed || !saved.email_enabled" @click="test('email')">发送测试邮件</button><button :disabled="busy || changed || !saved.webhook_enabled" @click="test('webhook')">发送测试 Webhook</button></div></section>
    <section class="panel"><div class="panel-heading"><h2>投递记录</h2><button :disabled="busy" @click="loadRecords(0)">刷新记录</button></div><div class="notification-tests"><label>状态<select v-model="status" :disabled="busy" @change="loadRecords(0)"><option value="">全部</option><option v-for="(name,key) in statuses" :key="key" :value="key">{{ name }}</option></select></label></div><p v-if="recordsError" role="alert" class="error-banner">{{ recordsError }}</p><ul v-else class="notification-records"><li v-for="item in records" :key="item.id"><div><strong>{{ item.metadata.test?'测试通知':'高风险通知' }} · {{ item.channel==='email'?'邮件':'Webhook' }}</strong><p>{{ statuses[item.status] || item.status }} · {{ item.attempts }} 次 · {{ date(item.created_at) }}</p><small>{{ item.id }}</small><p v-if="item.error" class="error-message">{{ item.error }}</p></div><button :disabled="busy" @click="detail(item)">详情</button><button v-if="item.status==='failed' && item.attempts<3" :disabled="busy || new Date(item.expires_at)<=new Date()" @click="retry(item)">重试</button></li><li v-if="!records.length" class="muted">暂无符合条件的记录。</li></ul><footer><span>{{ total }} 条</span><button :disabled="busy || !offset" @click="loadRecords(offset-25)">上一页</button><button :disabled="busy || offset+25>=total" @click="loadRecords(offset+25)">下一页</button></footer></section>
    <section v-if="selected" class="panel notification-detail"><div class="panel-heading"><h2>投递详情</h2><button @click="selected=null">关闭</button></div><pre>{{ JSON.stringify(selected.delivery.metadata,null,2) }}</pre><ul><li v-for="(step,index) in selected.history" :key="index">第 {{ step.attempt }} 次 · {{ statuses[step.status] || step.status }} · {{ date(step.created_at) }}<p v-if="step.error">{{ step.error }}</p></li></ul><p v-if="!selected.history.length" class="muted">尚无发送尝试。</p></section>
  </div>
</template>
<script setup>
import {computed,onMounted,onUnmounted,ref} from 'vue';
import {getNotificationConfig,saveNotificationConfig,testNotification,listNotifications,getNotification,retryNotification} from './adminApi.js';
const emit=defineEmits(['busy-change']);const draft=ref(null),saved=ref({}),baseline=ref(''),loading=ref(false),busy=ref(false),error=ref(''),message=ref(''),recordsError=ref(''),records=ref([]),total=ref(0),offset=ref(0),status=ref(''),selected=ref(null);
const statuses={queued:'等待发送',mail_queued:'已进入邮件队列',sending:'发送中',accepted:'对端已接收',failed:'失败',expired:'已过期',config_changed:'配置已变化',quota_limited:'额度不足，已跳过',unavailable:'渠道不可用，已跳过'};
const date=value=>value?new Date(value).toLocaleString():'未记录';
const clean=d=>JSON.stringify({...d,current_password:''});const dirty=computed(()=>draft.value&&(JSON.stringify(draft.value)!==baseline.value));const changed=computed(()=>draft.value&&clean(draft.value)!==clean(JSON.parse(baseline.value)));
defineExpose({hasUnsavedChanges:dirty,isBusy:busy});
let disposed=false;
onUnmounted(()=>{disposed=true});
function setBusy(value){busy.value=value;if(!disposed)emit('busy-change',value)}
async function load(){if(busy.value || dirty.value&&!window.confirm('放弃未保存修改并重新加载？'))return;loading.value=true;error.value='';draft.value=null;try{saved.value=await getNotificationConfig();const c=saved.value;draft.value={revision:c.revision,email_enabled:c.email_enabled,recipient:c.recipient,webhook_enabled:c.webhook_enabled,endpoint:'',secret:'',threshold:c.threshold,daily_limit:c.daily_limit,retention_enabled:c.retention_enabled,retention_days:c.retention_days,current_password:''};baseline.value=JSON.stringify(draft.value)}catch(e){error.value=e.message}finally{loading.value=false}}
async function save(){if(busy.value||!dirty.value)return;if(!draft.value.current_password){error.value='请输入当前管理员密码';return}if(draft.value.retention_enabled&&(!saved.value.retention_enabled||draft.value.retention_days<saved.value.retention_days)&&!window.confirm('启用或缩短日志保留期会清理过期终态运行记录，页面无法撤销；安全操作审计始终保留。确认已备份并保存？'))return;setBusy(true);error.value='';message.value='';try{const result=await saveNotificationConfig({...draft.value});saved.value=result;draft.value={...draft.value,revision:result.revision,endpoint:'',secret:'',current_password:''};baseline.value=JSON.stringify(draft.value);message.value='配置已保存；尚未发送测试通知。'}catch(e){error.value=e.message}finally{setBusy(false)}}
async function loadRecords(next=0){if(busy.value)return;setBusy(true);recordsError.value='';try{const result=await listNotifications({status:status.value,offset:next});records.value=result.items;total.value=result.total;offset.value=result.offset}catch(e){recordsError.value=e.message;records.value=[]}finally{setBusy(false)}}
async function test(channel){if(busy.value||changed.value||!window.confirm('确认向已保存渠道发送一条测试通知？'))return;setBusy(true);error.value='';message.value='';try{const result=await testNotification({revision:saved.value.revision,channel});message.value=`测试请求已处理：${statuses[result.status]||result.status}。入队不代表已接收。`}catch(e){error.value=e.message}finally{setBusy(false)}await loadRecords(0)}
async function detail(item){if(busy.value)return;setBusy(true);error.value='';try{selected.value=await getNotification(item.id)}catch(e){error.value=e.message}finally{setBusy(false)}}
async function retry(item){if(busy.value||!window.confirm('重试可能重复投递，确认接收方按投递 ID 去重后继续？'))return;setBusy(true);error.value='';try{await retryNotification(item.id,{revision:item.revision});message.value='已请求重试，请刷新查看实际结果。'}catch(e){error.value=e.message}finally{setBusy(false)}await loadRecords(offset.value)}
onMounted(async()=>{await load();if(!disposed)await loadRecords(0)});
</script>
<style scoped>
.notification-settings{display:grid;gap:20px}.notification-settings form,.notification-tests,.notification-detail>pre,.notification-detail>ul{padding:24px}.notification-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.check{display:flex;align-items:center;gap:10px}.check input{width:auto;margin:0}.notification-settings small{display:block;line-height:1.6;color:#7c858d;margin-top:8px}.notification-settings select{font:inherit;border:1px solid #dce1e4;border-radius:7px;padding:10px;background:white;margin-top:8px;display:block}.notification-settings footer{display:flex;gap:12px;align-items:center;justify-content:flex-end;padding:20px 24px;border-top:1px solid #edf0f2}.notification-settings footer>small,.notification-settings footer>span{margin-right:auto}.notification-tests>button{margin-right:10px}.notification-records{list-style:none;padding:0;margin:0}.notification-records li{display:flex;align-items:center;gap:12px;padding:18px 24px;border-top:1px solid #edf0f2}.notification-records li>div{flex:1;min-width:0;overflow-wrap:anywhere}.notification-records p{font-size:12px;color:#77818a}.notification-detail pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px}.notification-detail li{margin-bottom:12px;font-size:13px}@media(max-width:640px){.notification-fields{grid-template-columns:1fr}.notification-settings form,.notification-tests{padding:16px}.notification-settings footer,.notification-records li{flex-wrap:wrap;padding:16px}.notification-records li>div{flex-basis:100%}}
</style>
