import {mount,flushPromises} from '@vue/test-utils';
import {it,expect,afterEach,vi} from 'vitest';
import Operations from './Operations.vue';
import {setAdminApiTransport,resetAdminApi} from './adminApi.js';
let wrapper;afterEach(()=>{wrapper?.unmount();resetAdminApi();vi.restoreAllMocks()});
it('uses real overview values and clears stale metrics after failure',async()=>{let fail=false;setAdminApiTransport(r=>{if(fail)throw Error('读取失败');expect(r.riskPath).toContain('days=7');return {days:7,accounts:42,unknown_account_dates:12,unknown_publication_dates:3,mock_enabled:false}});wrapper=mount(Operations,{props:{mode:'overview'}});await flushPromises();expect(wrapper.text()).toContain('42');expect(wrapper.text()).toContain('账号 12 个');expect(wrapper.text()).toContain('不计入新增');fail=true;await wrapper.get('.panel-heading button').trigger('click');await flushPromises();expect(wrapper.text()).toContain('读取失败');expect(wrapper.find('.operations-metrics').exists()).toBe(false)});
it('shows dependency failure separately from missing configuration',async()=>{setAdminApiTransport(()=>({postgres:{status:'healthy',latency_ms:2},redis:{status:'not_configured'},media:{status:'unavailable'},mail_queue:null,encryption_key_loaded:true}));wrapper=mount(Operations,{props:{mode:'system'}});await flushPromises();expect(wrapper.text()).toContain('不可用');expect(wrapper.text()).toContain('未配置');expect(wrapper.text()).toContain('队列读取失败');expect(wrapper.text()).toContain('不代表备份完成')});
it('keeps the reclamation result visible and blocks parent refresh while a purge is pending',async()=>{
  let finish;const calls=[];setAdminApiTransport(r=>{calls.push(r);if(r.method==='POST')return new Promise(resolve=>{finish=resolve});if(r.riskPath==='media/orphans')return {items:[{id:'media.test',name:'example.txt',size:5}]};return {mail_queue:{}}});
  wrapper=mount(Operations,{props:{mode:'system'}});await flushPromises();expect(calls).toHaveLength(1);
  await wrapper.get('[data-testid=media-inspect]').trigger('click');await flushPromises();await wrapper.get('.reclaim-row button').trigger('click');await wrapper.get('[data-testid=media-confirm]').trigger('click');
  expect(wrapper.get('.panel-heading button').element.disabled).toBe(true);expect(wrapper.emitted('busy-change').at(-1)).toEqual([true]);await wrapper.get('.panel-heading button').trigger('click');expect(calls).toHaveLength(3);
  finish({removed:true});await flushPromises();expect(wrapper.get('.panel-heading button').element.disabled).toBe(false);expect(wrapper.text()).toContain('本地副本未删除');expect(wrapper.emitted('busy-change').at(-1)).toEqual([false]);
});
it('requires export confirmation and preserves server pagination totals',async()=>{const calls=[];setAdminApiTransport(r=>{calls.push(r.riskPath);return {items:[{id:'1',action:'request_failed',result:'failure',details:{http_status:403}}],total:510,offset:r.riskPath.includes('offset=25')?25:0,limit:25}});wrapper=mount(Operations,{props:{mode:'audit'}});await flushPromises();expect(wrapper.text()).toContain('请求失败');const confirm=vi.spyOn(window,'confirm').mockReturnValue(false);await wrapper.get('.operations-filters button[type=button]').trigger('click');expect(confirm).toHaveBeenCalled();expect(calls.some(p=>p.includes('export'))).toBe(false);await wrapper.findAll('.operations-pagination button')[1].trigger('click');await flushPromises();expect(calls.at(-1)).toContain('offset=25')});
