<template>
  <section class="panel">
    <form class="risk-filters" @submit.prevent="load(0)"><input v-model="q" aria-label="搜索举报" placeholder="内容 ID、举报者或原因"><select v-model="status" aria-label="举报状态"><option value="">全部状态</option><option v-for="(label,key) in reportStatuses" :key="key" :value="key">{{ label }}</option></select><select v-model="category" aria-label="举报类型"><option value="">全部类型</option><option v-for="(label,key) in riskCategories" :key="key" :value="key">{{ label }}</option></select><select v-model="priority" aria-label="优先级"><option value="">全部优先级</option><option value="high">高优先级</option><option value="normal">普通</option></select><button :disabled="loading || busy">查询</button><button type="button" :disabled="loading || busy" @click="download">导出元数据</button></form>
    <p v-if="error" role="alert" class="error-banner">{{ error }}</p><p v-if="message" role="status" class="success-message">{{ message }}</p>
    <p v-if="loading" class="empty-state" role="status">正在加载举报…</p>
    <div v-else class="table-scroll"><table class="data-table"><thead><tr><th>内容 / 举报原因</th><th>类型</th><th>状态</th><th>负责人</th><th>提交时间</th><th></th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td><strong>{{ row.target_id }}</strong><p class="muted risk-excerpt">{{ row.reason }}</p></td><td>{{ riskCategories[row.category] }}<small v-if="row.priority==='high'"> · 高优先级</small></td><td>{{ reportStatuses[row.status] }}</td><td>{{ row.assignee || '未分派' }}</td><td>{{ new Date(row.created_at).toLocaleString() }}</td><td><button :disabled="busy" data-testid="report-open" @click="open(row.id)">查看</button></td></tr></tbody></table><p v-if="!rows.length" class="empty-state">没有匹配的举报</p></div>
    <footer class="provider-footer"><span class="muted">{{ total }} 件 · 每页 25 件</span><div class="risk-actions"><button :disabled="loading || busy || offset===0" @click="load(offset-25)">上一页</button><button :disabled="loading || busy || offset+25>=total" @click="load(offset+25)">下一页</button></div></footer>
  </section>
  <section v-if="detail" ref="detailPanel" class="panel risk-detail">
    <div class="panel-heading"><h2>举报详情 · {{ reportStatuses[detail.status] }}</h2><button :disabled="busy" @click="close">关闭</button></div>
    <p>{{ riskCategories[detail.category] }} · {{ detail.reporter }}</p><blockquote>{{ detail.reason }}</blockquote>
    <details><summary>被举报的公开内容：{{ detail.target?.title || detail.target_id }}</summary><pre class="risk-preview">{{ detail.target?.content }}</pre><pre v-if="detail.target?.kind==='collection'" class="risk-preview">{{ JSON.stringify(detail.target.members,null,2) }}</pre></details>
    <div class="risk-rule-result"><strong>当前安全规则复核 · {{ detail.rules?.score || 0 }} 分</strong><p class="muted">{{ detail.rules?.notice }}</p><p v-for="hit in detail.rules?.hits" :key="hit.id">{{ hit.name }}：{{ hit.words.join('、') }}</p></div>
    <form v-if="['pending','processing'].includes(detail.status)" @submit.prevent="save"><fieldset :disabled="busy"><div class="risk-filters"><label>处置<select v-model="action" data-testid="report-action"><option value="start">开始处理</option><option value="assign">分派负责人</option><option value="dismiss">驳回举报</option><option value="offline">下架并结案</option></select></label><label>优先级<select v-model="editPriority"><option value="normal">普通</option><option value="high">高</option></select></label><label v-if="action==='assign'">负责人<select v-model="assignee" required><option value="">选择运营管理员</option><option v-for="email in assignees" :key="email">{{ email }}</option></select></label></div><label>处置原因<textarea v-model="reason" data-testid="report-reason" maxlength="1000" required placeholder="填写核查依据；结案原因会向举报者展示"></textarea></label><button class="primary" :disabled="!reason.trim()">{{ busy?'正在提交…':'确认处置' }}</button></fieldset></form>
    <p v-else><strong>结案原因：</strong>{{ detail.resolution }}</p>
    <h3>处置历史</h3><p v-if="!detail.events?.length" class="muted">尚无处置记录</p><div v-for="event in detail.events" :key="event.id" class="risk-event"><strong>{{ event.actor }} · {{ event.action }}</strong><time>{{ new Date(event.created_at).toLocaleString() }}</time><p>{{ event.reason }}</p></div>
  </section>
</template>
<script setup>
import { computed, nextTick, onMounted, ref } from 'vue';
import { exportReports, getReport, listReports, updateReport } from './adminApi.js';
import { reportStatuses, riskCategories } from './riskLabels.js';
const emit=defineEmits(['busy-change']);
const rows=ref([]),total=ref(0),offset=ref(0),q=ref(''),status=ref(''),category=ref(''),priority=ref('');
const loading=ref(false),busy=ref(false),error=ref(''),message=ref(''),detail=ref(null),assignees=ref([]),detailPanel=ref(null);
const action=ref('start'),reason=ref(''),assignee=ref(''),editPriority=ref('normal');
const hasUnsavedChanges=computed(()=>Boolean(detail.value && (reason.value || action.value!=='start' || editPriority.value!==detail.value.priority || assignee.value)));
defineExpose({hasUnsavedChanges,isBusy:busy});
const query=()=>({q:q.value,status:status.value,category:category.value,priority:priority.value});
function leave(){return !busy.value && (!hasUnsavedChanges.value || window.confirm('放弃未提交的处置草稿？'));}
async function load(next=offset.value){if(loading.value||busy.value)return;loading.value=true;error.value='';try{const data=await listReports({...query(),offset:next});if(!Array.isArray(data.items)||!Number.isInteger(data.total))throw Error('举报响应无效');rows.value=data.items;total.value=data.total;offset.value=next;assignees.value=data.assignees||[];}catch(e){error.value=e.message;}finally{loading.value=false;}}
async function open(id){if(!leave())return;error.value='';busy.value=true;emit('busy-change',true);try{const data=await getReport(id);if(data.id!==id||!Number.isInteger(data.revision))throw Error('详情响应无效');detail.value=data;reason.value='';action.value='start';assignee.value='';editPriority.value=data.priority;await nextTick();detailPanel.value?.scrollIntoView?.({block:'start',behavior:'smooth'});}catch(e){error.value=e.message;}finally{busy.value=false;emit('busy-change',false);}}
function close(){if(leave()){detail.value=null;reason.value='';}}
async function save(){if(busy.value||!reason.value.trim())return;if(['offline','dismiss'].includes(action.value)&&!window.confirm(action.value==='offline'?'确认下架公开内容并结案？不会删除用户本地副本。':'确认驳回举报？原因将对举报者可见。'))return;busy.value=true;emit('busy-change',true);error.value='';message.value='';const id=detail.value.id;try{const data=await updateReport(id,{revision:detail.value.revision,action:action.value,reason:reason.value,assignee:assignee.value||null,priority:editPriority.value});if(data.id!==id||data.revision!==detail.value.revision+1)throw Error('服务端未确认处置完成');detail.value=null;reason.value='';message.value='处置已保存';}catch(e){error.value=e.message;}finally{busy.value=false;emit('busy-change',false);}if(!detail.value){await load();await open(id);}}
async function download(){if(busy.value||!window.confirm('导出当前筛选前 500 件举报的元数据？不含举报者邮箱、描述或内容正文。'))return;busy.value=true;emit('busy-change',true);error.value='';try{const data=await exportReports(query());if(!Array.isArray(data.items))throw Error('导出响应无效');const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='promptark-reports.json';link.click();URL.revokeObjectURL(url);message.value=`已导出 ${data.items.length} 件，操作已审计`;}catch(e){error.value=e.message;}finally{busy.value=false;emit('busy-change',false);}}
onMounted(()=>load(0));
</script>
