<template><section>
 <div class="filters"><select v-model="status" :disabled="busy" aria-label="Skill 审核状态" @change="offset=0;load()"><option value="pending">待审核</option><option value="approved">已上架</option><option value="rejected">已退回</option><option value="withdrawn">已下架 / 撤回</option><option value="">全部状态</option></select><input v-model="query" :disabled="busy" placeholder="搜索 Skill" @keydown.enter="offset=0;load()"/><button :disabled="busy" @click="offset=0;load()">搜索 / 刷新</button></div>
 <p v-if="error" role="alert" class="error-message">{{ error }}</p><p v-if="notice" role="status">{{ notice }}</p>
 <template v-if="detail"><button :disabled="busy" @click="detail=null;bundle=null">← 返回审核列表</button><h2>{{ detail.title }}</h2><p>{{ detail.description }}</p><p>作者：{{ detail.publisher?.display_name }} · 分类：{{ detail.category }} · 许可：{{ detail.license }} · {{ statusName(detail.status) }}</p><p v-if="detail.reason">原因：{{ detail.reason }}</p><pre class="skill-document">{{ detail.body }}</pre><h3>全部文件 · {{ detail.files.length }}</h3><p>逐项查看声明、脚本和依赖；这里不执行文件。</p><div class="file-list"><button v-for="file in detail.files" :key="file.path" :disabled="busy" @click="readFile(file.path)">{{ file.path }} · {{ file.size }} B</button></div><pre v-if="fileText" class="skill-document">{{ fileText }}</pre><button :disabled="busy" @click="downloadBundle">下载完整审阅包（JSON）</button><p>文件包 SHA-256：{{ detail.digest }}</p>
 <label v-if="detail.status==='pending'"><input v-model="confirmed" type="checkbox" :disabled="busy"/>已核对完整文件清单、公开许可与依赖</label><label class="reason">审核说明 / 退回或下架原因<textarea v-model="reason" maxlength="2000" rows="3" :disabled="busy"/></label><div class="actions"><button v-if="detail.status==='pending'" :disabled="busy||!confirmed" @click="review('approved')">审核通过</button><button v-if="detail.status==='pending'" :disabled="busy||!reason.trim()" @click="review('rejected')">退回修改</button><button v-if="detail.status==='approved'" :disabled="busy||!reason.trim()" @click="review('withdrawn')">下架</button></div><ul><li v-for="(entry,index) in detail.history" :key="index">{{ entry.at }} · {{ statusName(entry.status) }} · {{ entry.reason }}</li></ul></template>
 <template v-else><p>{{ busy?'正在加载…':`共 ${total} 条` }}</p><table><thead><tr><th>Skill</th><th>发布者</th><th>许可</th><th>状态</th><th></th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{ item.title }}</td><td>{{ item.publisher?.display_name }}</td><td>{{ item.license }}</td><td>{{ statusName(item.status) }}</td><td><button :disabled="busy" @click="open(item.id)">查看完整文件</button></td></tr></tbody></table><p v-if="!items.length&&!busy&&!error">暂无对应投稿。</p><div class="actions"><button :disabled="busy||offset===0" @click="offset-=24;load()">上一页</button><button :disabled="busy||offset+24>=total" @click="offset+=24;load()">下一页</button></div></template>
 </section></template>
<script setup>
import {ref,watch,onMounted} from 'vue';import {skillReviewRequest} from './adminApi.js';
const emit=defineEmits(['busy-change']);const items=ref([]),total=ref(0),offset=ref(0),status=ref('pending'),query=ref(''),busy=ref(false),error=ref(''),notice=ref(''),detail=ref(null),bundle=ref(null),confirmed=ref(false),reason=ref(''),fileText=ref('');
const statusName=v=>({pending:'待审核',approved:'已上架',rejected:'已退回',withdrawn:'已撤回 / 下架'})[v]||v;
async function run(task){if(busy.value)return;busy.value=true;error.value='';try{return await task();}catch(e){error.value=String(e.message||e);}finally{busy.value=false;}}
async function load(){await run(async()=>{const result=await skillReviewRequest('?'+new URLSearchParams({status:status.value,q:query.value,offset:offset.value}));items.value=result.items;total.value=result.total;});}
async function open(id){await run(async()=>{detail.value=await skillReviewRequest('/'+id);bundle.value=null;confirmed.value=false;reason.value='';fileText.value='';});}
async function getBundle(){if(!bundle.value){const result=await skillReviewRequest('/'+detail.value.id+'/bundle');if(result.digest!==detail.value.digest)throw new Error('文件包已变化，请重新加载');bundle.value=result.bundle;}return bundle.value;}
async function readFile(path){await run(async()=>{const b=await getBundle();const file=b.files.find(f=>f.path===path);if(!file)throw new Error('文件不存在');try{const raw=Uint8Array.from(atob(file.content),c=>c.charCodeAt(0));if(raw.length>1024*1024){fileText.value='文件超过 1 MiB，请下载完整包检查。';return;}fileText.value=new TextDecoder('utf-8',{fatal:true}).decode(raw);}catch{fileText.value='这是二进制文件，请下载完整包检查。';}});}
async function downloadBundle(){await run(async()=>{const b=await getBundle(),url=URL.createObjectURL(new Blob([JSON.stringify(b,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=b.name+'.skill.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});}
async function review(next){const success=await run(async()=>{await skillReviewRequest('/'+detail.value.id+'/review','POST',{status:next,reason:reason.value,expected_status:detail.value.status});return true;});if(success){notice.value='审核结果已保存';detail.value=null;bundle.value=null;await load();}}
watch(busy,v=>emit('busy-change',v),{flush:'sync'});onMounted(load);
</script>
<style scoped>.skill-document{white-space:pre-wrap;overflow-wrap:anywhere;max-height:50vh;overflow:auto;padding:20px;background:var(--surface-alt,#f5f5f5);border:1px solid #ddd;border-radius:8px;font:12px/1.8 monospace}.file-list{display:flex;flex-wrap:wrap;gap:8px;margin:16px 0}.reason{display:grid;gap:8px;margin:16px 0}.filters,.actions{display:flex;gap:10px;margin:16px 0}.reason textarea{width:100%}table{width:100%;text-align:left}td,th{padding:14px;border-bottom:1px solid #ddd}</style>
