import { mount, flushPromises } from '@vue/test-utils';
import { beforeEach, afterEach, expect, it, vi } from 'vitest';
import SettingsModal from './SettingsModal.vue';
import MyPublications from './MyPublications.vue';
import WorkbenchShell from './WorkbenchShell.vue';
import { resetMemoryLibrary, listLocalPrompts } from '../platform/library.js';
import { resetMemorySession, setSessionTransport, loginSession } from '../platform/session.js';
import * as square from '../platform/square.js';
import * as tauri from '../platform/tauri.js';
let w;
beforeEach(() => { resetMemoryLibrary(); resetMemorySession(); square.resetSquare(); });
afterEach(() => { w?.unmount(); vi.restoreAllMocks(); delete window.__TAURI_INTERNALS__; });
it('previews a dropped file and writes only after confirmation; rejects invalid files', async () => {
  w = mount(SettingsModal, { props: { initialPage: 'data' } }); await flushPromises();
  const file = new File(['{"prompts":[{"title":"文件导入","content":"原文"}]}'], 'prompts.json', { type: 'application/json' });
  await w.get('[data-testid=import-drop]').trigger('drop', { dataTransfer: { files: [file] } });
  await vi.waitFor(() => expect(w.find('[data-testid=import-preview]').exists()).toBe(true));
  expect(await listLocalPrompts()).toHaveLength(0);
  await w.findAll('button').find(b => b.text() === '确认导入').trigger('click'); await flushPromises();
  expect((await listLocalPrompts())[0].content).toBe('原文');
  await w.get('[data-testid=import-drop]').trigger('drop', { dataTransfer: { files: [new File(['broken'], 'invalid.json')] } });
  await vi.waitFor(() => expect(w.get('[data-testid=backup-error]').text()).toContain('读取文件失败'));
  expect(await listLocalPrompts()).toHaveLength(1);
});
it('keeps the restore path when the native file picker is cancelled', async () => {
  w = mount(SettingsModal); await flushPromises();
  window.__TAURI_INTERNALS__ = {};
  const choose = vi.spyOn(tauri, 'invokeCommand').mockResolvedValueOnce(null).mockResolvedValueOnce('/tmp/selected.sqlite');
  await w.get('[data-settings-page=data]').trigger('click');
  const path = w.get('input[placeholder="/path/to/promptark.sqlite"]');
  await path.setValue('/tmp/original.sqlite');
  await w.get('[data-testid=choose-restore]').trigger('click'); await flushPromises();
  expect(path.element.value).toBe('/tmp/original.sqlite');
  await w.get('[data-testid=choose-restore]').trigger('click'); await flushPromises();
  expect(path.element.value).toBe('/tmp/selected.sqlite');
  expect(choose.mock.calls.map(c => c[0])).toEqual(['choose_library_backup', 'choose_library_backup']);
});
it('isolates publication responses across accounts and offers a retry on failure', async () => {
  let resolve;
  vi.spyOn(square, 'listMyPublications').mockImplementationOnce(() => new Promise(r => { resolve = r; })).mockRejectedValueOnce(Error('离线')).mockResolvedValueOnce([{ id: 'b', title: 'B 的稿件', status: 'pending' }]);
  w = mount(MyPublications, { props: { session: { email: 'a', loggedIn: true } } });
  await w.setProps({ session: { email: 'b', loggedIn: true } }); await flushPromises();
  resolve([{ id: 'a', title: 'A 的稿件' }]); await flushPromises();
  expect(w.text()).not.toContain('A 的稿件');
  expect(w.text()).toContain('读取失败');
  await w.findAll('button').find(b => b.text() === '重试').trigger('click'); await flushPromises();
  expect(w.text()).toContain('B 的稿件');
});
it('protects settings drafts before opening the standalone publications page', async () => {
  setSessionTransport(async () => ({ email: 'a@example.test', access_token: 'token' }));
  await loginSession({ email: 'a@example.test', password: 'pass' });
  square.setMineTransport(async () => []);
  w = mount(WorkbenchShell); await flushPromises();
  await w.get('[data-testid=open-settings]').trigger('click'); await flushPromises();
  await w.get('[data-settings-page=models]').trigger('click'); await w.get('[data-testid=default-model]').setValue('草稿');
  await w.get('[data-settings-page=account]').trigger('click'); await w.get('[data-testid=settings-publications]').trigger('click');
  expect(w.find('[data-testid=publications-page]').exists()).toBe(false);
  await w.get('[data-testid=cancel-settings-action]').trigger('click');
  await w.get('[data-settings-page=models]').trigger('click');
  expect(w.get('[data-testid=default-model]').element.value).toBe('草稿');
});
