import { mount, flushPromises } from '@vue/test-utils';
import { beforeEach, afterEach, expect, it, vi } from 'vitest';
import WorkbenchShell from './WorkbenchShell.vue';
import * as library from '../platform/library.js';
import { resetMemorySession } from '../platform/session.js';
import { resetSquare, setSquareTransport, setSquareContentTransport } from '../platform/square.js';
let w;
beforeEach(() => { library.resetMemoryLibrary(); resetMemorySession(); resetSquare(); });
afterEach(() => { w?.unmount(); vi.restoreAllMocks(); });
it('reads without writing and returns to the same query; explicit edit updates the reading page', async () => {
  const p = await library.createLocalPrompt({ title: '模板', content: '原文' });
  w = mount(WorkbenchShell); await flushPromises();
  await w.get('.inline-search input').setValue('模板'); await flushPromises();
  await w.get('.prompt-title').trigger('click');
  expect(w.get('[data-testid=local-detail]').text()).toContain('原文');
  expect(w.find('[data-testid=prompt-editor]').exists()).toBe(false);
  expect((await library.listLocalPrompts())[0].use_count).toBe(0);
  await w.get('[data-testid=detail-edit]').trigger('click');
  await w.get('[data-testid=prompt-editor] textarea').setValue('新文');
  await w.get('[data-testid=prompt-editor] .primary-button').trigger('click'); await flushPromises();
  expect(w.get('[data-testid=local-detail]').text()).toContain('新文');
  await w.get('[data-testid=local-detail] .page-back').trigger('click');
  expect(w.get('.inline-search input').element.value).toBe('模板');
  expect((await library.listLocalPrompts())[0].id).toBe(p.id);
});
it('exposes the same actions from the visible more button and does not count failed quick copies', async () => {
  await library.createLocalPrompt({ title: '常用', content: '正文' });
  Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: vi.fn().mockRejectedValueOnce(Error('拒绝')).mockResolvedValue(undefined) } });
  w = mount(WorkbenchShell); await flushPromises();
  await w.get('[data-testid=card-more]').trigger('click');
  expect(w.get('[data-action=edit]').text()).toBe('编辑');
  await w.get('[role=menu]').trigger('keydown', {key:'Escape'});
  await w.findAll('.card-footer button').find(b=>b.text()==='使用').trigger('click'); await flushPromises();
  expect(w.get('[data-testid=use-modal]').text()).toContain('复制失败');
  expect((await library.listLocalPrompts())[0].use_count).toBe(0);
  await w.get('[data-testid=use-next]').trigger('click'); await flushPromises();
  expect((await library.listLocalPrompts())[0].use_count).toBe(1);
});
it('opens a downloaded copy without a second content request or duplicate write', async () => {
  setSquareTransport(async () => [{ id: 'remote', kind: 'prompt', title: '远端' }]);
  const content = vi.fn(async () => ({ id: 'remote', title: '远端', content: '副本正文' }));
  setSquareContentTransport(content);
  w = mount(WorkbenchShell); await flushPromises();
  await w.get('[data-space=square]').trigger('click'); await flushPromises();
  await w.get('[data-testid=download-square]').trigger('click'); await flushPromises();
  await w.get('[data-testid=download-square]').trigger('click'); await flushPromises();
  expect(w.get('[data-testid=local-detail]').text()).toContain('副本正文');
  expect(content).toHaveBeenCalledTimes(1);
  expect(await library.listLocalPrompts()).toHaveLength(1);
});
it('supports arrow navigation in the more menu and returns focus on Escape', async () => {
  await library.createLocalPrompt({ title: '键盘', content: '正文' });
  w = mount(WorkbenchShell, { attachTo: document.body }); await flushPromises();
  const more = w.get('[data-testid=card-more]'); more.element.focus(); await more.trigger('click'); await flushPromises();
  expect(document.activeElement).toBe(w.get('[data-action=edit]').element);
  await w.get('[role=menu]').trigger('keydown', { key: 'ArrowDown' });
  expect(document.activeElement).toBe(w.get('[data-action=duplicate]').element);
  await w.get('[role=menu]').trigger('keydown', { key: 'Escape' }); await flushPromises();
  expect(document.activeElement).toBe(more.element);
});

it('bounds card text while searching, reading and editing the full original', async () => {
  const content = '写'.repeat(239) + '😀'.repeat(2000) + '全文末尾标记';
  await library.createLocalPrompt({ title: '超长模板', content });
  w = mount(WorkbenchShell); await flushPromises();
  await w.get('.inline-search input').setValue('全文末尾标记'); await flushPromises();
  const excerpt = w.get('.prompt-excerpt').text();
  expect(Array.from(excerpt)).toHaveLength(241);
  expect(excerpt).toBe('写'.repeat(239) + '😀…');
  await w.get('.prompt-title').trigger('click');
  expect(w.get('.reading-content').text()).toBe(content);
  await w.get('[data-testid=detail-edit]').trigger('click');
  expect(w.get('[data-testid=prompt-editor] textarea').element.value).toBe(content);
});
