import {mount,flushPromises} from '@vue/test-utils';import {afterEach,beforeEach,it,expect,vi} from 'vitest';
import SkillCommunity from './SkillCommunity.vue';import {setSkillMarketTransport} from '../platform/skillMarket.js';
let w;const item={id:'one',title:'My skill',description:'Description',category:'ai',license:'MIT',status:'approved',digest:'sha',publisher:{display_name:'作者'},files:[{path:'SKILL.md',size:8}],body:'<script>no()</script>'};
const click=async text=>{await w.findAll('button').find(b=>b.text()===text).trigger('click');await flushPromises();};
afterEach(()=>{w?.unmount();setSkillMarketTransport(null);});
it('loads real community items, previews safely and installs the same immutable bundle',async()=>{const transport=vi.fn(async(action)=>action==='browse'?{items:[item],total:1,category_counts:{ai:1}}:action==='detail'?item:{bundle:{name:'my-skill',files:[]},digest:'sha'});setSkillMarketTransport(transport);w=mount(SkillCommunity);await flushPromises();expect(w.text()).toContain('共 1 个 Skill');await w.get('.skills-list-row').trigger('click');await flushPromises();expect(w.find('script').exists()).toBe(false);await click('安装到智能体…');expect(w.emitted('install')[0][0].digest).toBe('sha');expect(transport).toHaveBeenCalledWith('bundle',{id:'one'});});
it('blocks changed bundles and retries without a false installation',async()=>{setSkillMarketTransport(async(action)=>action==='browse'?{items:[item],total:1,category_counts:{ai:1}}:action==='detail'?item:{bundle:{},digest:'changed'});w=mount(SkillCommunity);await flushPromises();await w.get('.skills-list-row').trigger('click');await flushPromises();await click('安装到智能体…');expect(w.get('[role=alert]').text()).toContain('版本已变化');expect(w.emitted('install')).toBeUndefined();});
it('requires explicit withdrawal and sends the current review status',async()=>{const t=vi.fn(async action=>action==='detail'?item:{items:[item],total:1,category_counts:{ai:1}});setSkillMarketTransport(t);w=mount(SkillCommunity,{props:{mine:true}});await flushPromises();await w.get('.skills-list-row').trigger('click');await flushPromises();await click('撤回发布');expect(t.mock.calls.some(([a])=>a==='withdraw')).toBe(false);await click('确认撤回');expect(t).toHaveBeenCalledWith('withdraw',{id:'one',body:{status:'withdrawn',expected_status:'approved',reason:'作者撤回'}});});
it('guides an empty community to GitHub and hides pagination until there are multiple pages',async()=>{
 let total=0;setSkillMarketTransport(async()=>({items:total?[item]:[],total,category_counts:total?{ai:total}:{}}));w=mount(SkillCommunity);await flushPromises();
 expect(w.text()).toContain('社区还没有公开的 Skill');expect(w.find('.skills-pagination').exists()).toBe(false);await w.get('.community-empty button').trigger('click');expect(w.emitted('browse-github')).toHaveLength(1);
 total=24;await w.get('[aria-label="刷新"]').trigger('click');await flushPromises();expect(w.find('.skills-pagination').exists()).toBe(false);
 total=25;await w.get('[aria-label="刷新"]').trigger('click');await flushPromises();expect(w.find('.skills-pagination').exists()).toBe(true);expect(w.text()).toContain('第 1 / 2 页');
});
it('distinguishes a search with no matches from an author without publications',async()=>{
 setSkillMarketTransport(async()=>({items:[],total:0,category_counts:{}}));w=mount(SkillCommunity,{props:{mine:true}});await flushPromises();expect(w.text()).toContain('你还没有发布 Skill');
 await w.get('input').setValue('missing');await w.get('form').trigger('submit');await flushPromises();expect(w.text()).toContain('没有找到匹配的 Skill');expect(w.find('.community-empty button').exists()).toBe(false);
});
