[package]
name = "cuetuck"
version = "0.1.0-beta.20"
description = "CueTuck desktop"
edition = "2021"

[lib]
name = "cuetuck_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
regex = "1"
rusqlite = { version = "0.32", features = ["bundled", "backup"] }
tempfile = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
image = { version = "0.25", default-features = false, features = ["png", "jpeg", "gif", "webp"] }
semver = "1"
tauri = { version = "2", features = ["macos-private-api"] }
uuid = { version = "1", features = ["v4"] }
keyring = { version = "3", features = ["apple-native", "windows-native"] }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "multipart", "system-proxy"] }
sha2 = "0.10"
open = "5"
tauri-plugin-updater = "2"
tauri-plugin-dialog = "2"
url = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "sync"] }
yaml-rust2 = "0.13.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"
enigo = "0.2"

[target.'cfg(target_os = "macos")'.dependencies]
objc2-app-kit = { version = "0.3.2", default-features = false, features = ["std", "libc", "NSRunningApplication", "NSWorkspace"] }

[features]
updater-artifact-test = ["tauri/test"]
